/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from "./src/context"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CompanyCreateInput: { // input type
    description: string; // String!
    employee?: NexusGenInputs['EmployeeCreateNestedManyWithoutCompanyInput'] | null; // EmployeeCreateNestedManyWithoutCompanyInput
    name: string; // String!
    symbol: string; // String!
  }
  CompanyUpdateInput: { // input type
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    employee?: NexusGenInputs['EmployeeUpdateManyWithoutCompanyInput'] | null; // EmployeeUpdateManyWithoutCompanyInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    symbol?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CompanyWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  EmployeeCreateNestedManyWithoutCompanyInput: { // input type
    connect?: NexusGenInputs['EmployeeWhereUniqueInput'][] | null; // [EmployeeWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['EmployeeCreateOrConnectWithoutCompanyInput'][] | null; // [EmployeeCreateOrConnectWithoutCompanyInput!]
    create?: NexusGenInputs['EmployeeCreateWithoutCompanyInput'][] | null; // [EmployeeCreateWithoutCompanyInput!]
  }
  EmployeeCreateOrConnectWithoutCompanyInput: { // input type
    create: NexusGenInputs['EmployeeCreateWithoutCompanyInput']; // EmployeeCreateWithoutCompanyInput!
    where: NexusGenInputs['EmployeeWhereUniqueInput']; // EmployeeWhereUniqueInput!
  }
  EmployeeCreateWithoutCompanyInput: { // input type
    age: number; // Int!
    name: string; // String!
  }
  EmployeeScalarWhereInput: { // input type
    AND?: NexusGenInputs['EmployeeScalarWhereInput'][] | null; // [EmployeeScalarWhereInput!]
    NOT?: NexusGenInputs['EmployeeScalarWhereInput'][] | null; // [EmployeeScalarWhereInput!]
    OR?: NexusGenInputs['EmployeeScalarWhereInput'][] | null; // [EmployeeScalarWhereInput!]
    age?: NexusGenInputs['IntFilter'] | null; // IntFilter
    companyId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  EmployeeUpdateManyMutationInput: { // input type
    age?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmployeeUpdateManyWithWhereWithoutCompanyInput: { // input type
    data: NexusGenInputs['EmployeeUpdateManyMutationInput']; // EmployeeUpdateManyMutationInput!
    where: NexusGenInputs['EmployeeScalarWhereInput']; // EmployeeScalarWhereInput!
  }
  EmployeeUpdateManyWithoutCompanyInput: { // input type
    connect?: NexusGenInputs['EmployeeWhereUniqueInput'][] | null; // [EmployeeWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['EmployeeCreateOrConnectWithoutCompanyInput'][] | null; // [EmployeeCreateOrConnectWithoutCompanyInput!]
    create?: NexusGenInputs['EmployeeCreateWithoutCompanyInput'][] | null; // [EmployeeCreateWithoutCompanyInput!]
    delete?: NexusGenInputs['EmployeeWhereUniqueInput'][] | null; // [EmployeeWhereUniqueInput!]
    deleteMany?: NexusGenInputs['EmployeeScalarWhereInput'][] | null; // [EmployeeScalarWhereInput!]
    disconnect?: NexusGenInputs['EmployeeWhereUniqueInput'][] | null; // [EmployeeWhereUniqueInput!]
    set?: NexusGenInputs['EmployeeWhereUniqueInput'][] | null; // [EmployeeWhereUniqueInput!]
    update?: NexusGenInputs['EmployeeUpdateWithWhereUniqueWithoutCompanyInput'][] | null; // [EmployeeUpdateWithWhereUniqueWithoutCompanyInput!]
    updateMany?: NexusGenInputs['EmployeeUpdateManyWithWhereWithoutCompanyInput'][] | null; // [EmployeeUpdateManyWithWhereWithoutCompanyInput!]
    upsert?: NexusGenInputs['EmployeeUpsertWithWhereUniqueWithoutCompanyInput'][] | null; // [EmployeeUpsertWithWhereUniqueWithoutCompanyInput!]
  }
  EmployeeUpdateWithWhereUniqueWithoutCompanyInput: { // input type
    data: NexusGenInputs['EmployeeUpdateWithoutCompanyInput']; // EmployeeUpdateWithoutCompanyInput!
    where: NexusGenInputs['EmployeeWhereUniqueInput']; // EmployeeWhereUniqueInput!
  }
  EmployeeUpdateWithoutCompanyInput: { // input type
    age?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmployeeUpsertWithWhereUniqueWithoutCompanyInput: { // input type
    create: NexusGenInputs['EmployeeCreateWithoutCompanyInput']; // EmployeeCreateWithoutCompanyInput!
    update: NexusGenInputs['EmployeeUpdateWithoutCompanyInput']; // EmployeeUpdateWithoutCompanyInput!
    where: NexusGenInputs['EmployeeWhereUniqueInput']; // EmployeeWhereUniqueInput!
  }
  EmployeeWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Company: { // root type
    description: string; // String!
    id: number; // Int!
    name: string; // String!
    symbol: string; // String!
  }
  Employee: { // root type
    age: number; // Int!
    id: number; // Int!
    name: string; // String!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Company: { // field return type
    description: string; // String!
    employee: NexusGenRootTypes['Employee'][]; // [Employee!]!
    id: number; // Int!
    name: string; // String!
    symbol: string; // String!
  }
  Employee: { // field return type
    age: number; // Int!
    id: number; // Int!
    name: string; // String!
  }
  Mutation: { // field return type
    createOneCompany: NexusGenRootTypes['Company']; // Company!
    deleteOneCompany: NexusGenRootTypes['Company'] | null; // Company
    updateOneCompany: NexusGenRootTypes['Company'] | null; // Company
  }
  Query: { // field return type
    companies: NexusGenRootTypes['Company'][]; // [Company!]!
    company: NexusGenRootTypes['Company'] | null; // Company
  }
}

export interface NexusGenFieldTypeNames {
  Company: { // field return type name
    description: 'String'
    employee: 'Employee'
    id: 'Int'
    name: 'String'
    symbol: 'String'
  }
  Employee: { // field return type name
    age: 'Int'
    id: 'Int'
    name: 'String'
  }
  Mutation: { // field return type name
    createOneCompany: 'Company'
    deleteOneCompany: 'Company'
    updateOneCompany: 'Company'
  }
  Query: { // field return type name
    companies: 'Company'
    company: 'Company'
  }
}

export interface NexusGenArgTypes {
  Company: {
    employee: { // args
      after?: NexusGenInputs['EmployeeWhereUniqueInput'] | null; // EmployeeWhereUniqueInput
      before?: NexusGenInputs['EmployeeWhereUniqueInput'] | null; // EmployeeWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    createOneCompany: { // args
      data: NexusGenInputs['CompanyCreateInput']; // CompanyCreateInput!
    }
    deleteOneCompany: { // args
      where: NexusGenInputs['CompanyWhereUniqueInput']; // CompanyWhereUniqueInput!
    }
    updateOneCompany: { // args
      data: NexusGenInputs['CompanyUpdateInput']; // CompanyUpdateInput!
      where: NexusGenInputs['CompanyWhereUniqueInput']; // CompanyWhereUniqueInput!
    }
  }
  Query: {
    companies: { // args
      after?: NexusGenInputs['CompanyWhereUniqueInput'] | null; // CompanyWhereUniqueInput
      before?: NexusGenInputs['CompanyWhereUniqueInput'] | null; // CompanyWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    company: { // args
      where: NexusGenInputs['CompanyWhereUniqueInput']; // CompanyWhereUniqueInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
}